#####################################################################################
#####################################################################################

########################  Mound data enrichment from available raster and spatial data

######################################################################################

# Goal
# Enrich mound dataset with elevation, slope and aspect, and calculate distance to nearest settlement boundary as well as to the national border.
# As inputs we use the 
# - master_sp sf object produced by 06_GetSpatial.R, 
# - ASTER DEM from JICA 1994, and 
# - vector files of settlement polygons for Bulgaria, Yambol with 15km buffer, and national border provided by JICA
# As OUTPUTs we expect:
# a new object (dataset enviro_Yamnds), simple feature with environmental indeces of 
# elevation, slope, aspect, distance to national border, distance to nearest settlement, 
# prominence at different radii.

# 
# Process
# 1.Load data
# 2.Check CRS everywhere for alignment with EPSG 32635
# 3.Sample rasters at points: I extract environmental data from rasters at mound coordinates by using
# the raster::extract() function
# 4. Calculate distance indeces via the  st_nearest_feature() and st_distance()
# 5. Calculate mound prominence/hierarchy via raster::extract() with perc() function
# 6. 
# Libraries
library(tidyverse)
library(raster)
library(rgdal)
library(FSA)
library(sf)

################################# LOAD INPUTS   ###########################################################################

df_name <- c("master_sp")
if (exists(df_name)){
  print("file exists")
  get(df_name)
}  else source("scripts/06_GetSpatial.R")



# Load ASTER raster, in this case ASTER DEM from JICA, projected to WGS82, UTM 35N

#Yam <- raster("E:/TRAP Workstation/Shared GIS/Satellite imagery/ASTER/DEM/ASTGTM_N42E026/prjYAM_DEM_N42E026.tif")
Yam <- raster("F:/Shared GIS/Satellite imagery/ASTER/DEM/ASTGTM_N42E026/prjYAM_DEM_N42E026.tif")
Yam # projected WGS84 35N raster 27m resolution, 4112x3053
Yaspect<- raster("F:/Shared GIS/Satellite imagery/ASTER/DEM/ASTGTM_N42E026/prjYAM_Aspect.tif")
Yslope<- raster("F:/Shared GIS/Satellite imagery/ASTER/DEM/ASTGTM_N42E026/prjYAM_Slope.tif")


# Load shapefiles of master_sp, urban areas, boundaries etc. generated by ArcGIS (1 spatial duplicate)

#mnd_shp <- st_read("C:/Users/Adela/Documents/Professional/Projects/MQNS/GIS/Vectors/200918VisitedMax.shp")
#Y_region <- st_read("F:/Shared GIS/Vector/Oxbow Shapefiles/13_Janouch/Area_borders_shp/Yambol_province_TRAP.shp")

bg_border <- st_read("F:/Shared GIS/Vector/Oxbow Shapefiles/Bulgaria_Border.shp")
Y_towns <- st_read("F:/Shared GIS/Vector/Oxbow Shapefiles/13_Janouch/Rivers_Roads_Settlements_Yambol/Modern_settlements_Yambol_TRAP.shp")
towns <- st_read("C:/Users/Adela/Documents/Professional/Projects/MQNS/GIS/Vectors/Yamurbanarea.shp") # towns within 15km buffer of Yambol boundary exported from JICA


################################# VISUAL CHECK - PLOT LOADED DATASETS ##########################################################################

# Visual check of the data
plot(Yam)
plot(master_sp$geometry, pch = 17, add = TRUE)
plot(towns$geometry, add = TRUE)

# Where are we in Bulgaria
plot(bg_border$geometry)
plot(towns$geometry, add = TRUE)
plot(master_sp$geometry, pch = 17, add = TRUE)

################################# CHECK CRS ##########################################################################

# Prerequisites to sampling - Coordinate system alignment

if (st_crs(Yam)==st_crs(master_sp)){
  print("all is copacetic, raster and mound sf object have the same projection")
} else {stop("raster and mound sf object do not have the same projection, fix it before proceeding")}# LOOKS GREAT

if (st_crs(bg_border)==st_crs(Y_towns)==st_crs(towns)){
  print("you can proceed, vector objects and mound sf object share projection")
} else {stop("vectors and mound sf object need to have the same projection, fix it before proceeding")}

################################# CALCULATE DISTANCE TO BG BORDER AND NEAREST TOWN ###########################################################################

# Distance from points to BG boundary

master_sp$distBG <-  st_distance(master_sp,bg_border)
master_sp$distBG[1:3,]


# Distance from mound points to nearest settlement

# This is a two-step process: 
# (1) selecting closest town via st_nearest and 
# nearest <-  try(st_nearest_feature(master_sp, towns))
# try() is a wrapper to run an expression that might fail and allow recovery
# (2) getting distance with st_distance
# distTown <- st_distance(master_sp, towns[st_nearest_feature(master_sp, towns),], by_element = TRUE)


# add result to dataframe
master_sp$distTown <- st_distance(master_sp, towns[st_nearest_feature(master_sp, towns),], by_element = TRUE)
head(master_sp,3)

################################# SAMPLE ELEVATION, ASPECT AND SLOPE AT MOUND COORDINATES ###########################################################################

# Prerequisite to sampling - a dataframe with coordinates alone
mound_coordinates <- data.frame(st_coordinates(master_sp)) # don't add TRAP yet


# Sample elevations at mound locations

master_sp$elevationAster <- raster::extract(Yam, mound_coordinates)
master_sp$slopeAster <-  raster::extract(Yslope, mound_coordinates)
master_sp$aspectAster <-  raster::extract(Yaspect, mound_coordinates)

# # If working with a table, you can create one with elevation, slope and aspect at mound locations
# 
# 
# enviro_Yammnds <- data.frame(mound_coordinates, master_sp$TRAP,
#                              elevation=
#                                raster::extract(Yam, mound_coordinates),
#                              slope=
#                                raster::extract(Yslope, mound_coordinates),
#                              aspect=
#                                raster::extract(Yaspect, mound_coordinates))



################################# PROMINENCE ###################################

# There is something rotten in the prominence below, as it always averages out to a random 50% (unlikely) ; when I tested with a subset 
# the numbers were closer to my epxectations, so maybe it's a lot of master_sp on a slope. 
# PROBLEM IS CONCEPTUAL: PROMINENCE IS ABOUT SPATIAL HIERARCHY, WHILE i WAS THINKING MORE OF VISIBILITY.
master_sp$prom250mbuff <- raster::extract(Yam,  # raster containing elevation data
                                               mound_coordinates, # centroids of master_sp
                                               buffer = 250,
                                               #buffer = 250, # actual buffer size in crs units, in this case 250m  or ca 22x22 cells around kernel
                                               fun = function(x){perc(x,x[length(x)/2],"lt", na.rm = FALSE, digits = 2)})


master_sp%>% 
  filter(prom250mbuff > 74) %>% 
  plot()


# Test with smaller subset to verify that the prominence values vary and are not random
mnd09shp <- master_sp %>% 
  filter(TRAP%in%mnd2009$TRAP)%>% 
  filter(TRAP < 8020)

mnd09_coordinates <- data.frame(st_coordinates(mnd09shp)) # don't add TRAP yet
test <- raster::extract(Yam,  # raster containing elevation data
                        mnd09_coordinates, # centroids of master_sp
                        buffer = 250,
                        #buffer = 250, # actual buffer size in crs units, in this case 250m  or ca 22x22 cells around kernel
                        fun = function(x){perc(x,x[length(x)/2],"lt", na.rm = FALSE, digits = 2)})
summary(test)
hist(test)


# Prominence at 1 and 2 and 5 km

enviro_Yammnds$prom1kmbuff <- raster::extract(Yam,  # raster containing elevation data
                                              mound_coordinates, # centroids of master_sp
                                              buffer = 1000, # actual buffer size in crs units, in this case 1000m  or ca 50x50 cells around kernel
                                              fun = function(x){perc(x,x[length(x)/2],"lt", na.rm = FALSE, digits = 2)})

enviro_Yammnds$prom2kmbuff <- raster::extract(Yam,  # raster containing elevation data
                                              mound_coordinates, # centroids of master_sp
                                              buffer = 2000,# actual buffer size in crs units, in this case 2000m  or ca 100x100 cells around kernel
                                              fun = function(x){perc(x,x[length(x)/2],"lt", na.rm = FALSE, digits = 2)})

enviro_Yammnds$prom3kmbuff <- raster::extract(Yam,  # raster containing elevation data
                                              mound_coordinates, # centroids of master_sp
                                              buffer = 3000,# actual buffer size in crs units, in this case 3000m  or ca 200x200 cells around kernel
                                              fun = function(x){perc(x,x[length(x)/2],"lt", na.rm = FALSE, digits = 2)})

enviro_Yammnds$prom5kmbuff <- raster::extract(Yam,  # raster containing elevation data
                                              mound_coordinates, # centroids of master_sp
                                              buffer = 5000,# actual buffer size in crs units, in this case 5000m  or ca 400x400 cells around kernel
                                              fun = function(x){perc(x,x[length(x)/2],"lt", na.rm = FALSE, digits = 2)})

enviro_Yammnds$prom10kmbuff <- raster::extract(Yam,  # raster containing elevation data
                                               mound_coordinates, # centroids of master_sp
                                               buffer = 10000,# actual buffer size in crs units, in this case 10000m  or ca 500X500 cells around kernel
                                               fun = function(x){perc(x,x[length(x)/2],"lt", na.rm = FALSE, digits = 2)})


hist(enviro_Yammnds$prom2kmbuff)


############################################## EXPORT DATA
master_sp$geometry
library(sf)
st_write(master_sp, "output_data/enriched_all.shp")
